spring:
  application:
    name: gopay-operations-cli
    version: 1.0
  profiles:
    active:
      - dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

logging:
  file:
    path: logs
