CREATE TABLE customers
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255),
    email  VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customerentity_email UNIQUE (email);